matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.context_filter:
      context_visible_first: true
      # escapes: '\\[\\`~]'
      delimiters:
      # Ignore jekyll magic commands {% ... %}
      - open: '{%'
        close: '%}'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
  - pyspelling.filters.html:
    comments: false
    attributes:
    - title
    - alt
    ignores:
    - :matches(code, pre)
    - a:matches(.magiclink-compare, .magiclink-commit)
    - span.keys
    - :matches(.MathJax_Preview, .md-nav__link, .md-footer-custom-text, .md-source__repository, .headerlink, .md-icon)
  sources:
  - '**/*.md'
  default_encoding: utf-8