matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    attributes:
    - title
    - alt
    ignores:
    - :matches(code, pre)
    - a:matches(.magiclink-compare, .magiclink-commit)
    - span.keys
    - :matches(.MathJax_Preview, .md-nav__link, .md-footer-custom-text, .md-source__repository, .headerlink, .md-icon)
  sources:
  - '**/*.md'
  default_encoding: utf-8