# baseurl: /blog
title: Kirill Dubovikov 
subtitle: Content-centric blogging
author: Kirill Dubovikov
simple_search: http://google.com/search
description: My thoughts on everything :)
name: Kirill's blog
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:categories/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
destination: 'docs'
keep_files: ['CNAME']
plugins:
  - jekyll-feed
feed:
  excerpt_only: true
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: nvim
git:
  branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: docs/
#   destination: ~/Git/clayh53.github.com/
